### ISSUE TITLE
Update features 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#17]
- [x] Change title to: **Key Features**
- [x] Design the icons to fit with description and theme

![image](https://user-images.githubusercontent.com/30463117/159827569-5a80bb71-f4e6-43b9-8a57-26cc886d216e.png)

Linkexpres features title and description:
![image](https://user-images.githubusercontent.com/30463117/159828207-0b4d05bc-d2cd-47c2-b4eb-f1ad08526a5d.png)

**Comment by russel0907** [comment]
Updated on features:
![Screenshot 2022-03-24 at 11-04-15 Linkexpres - Logistics Management System](https://user-images.githubusercontent.com/94702093/159834297-12460b7e-1255-4de5-9055-7789a5f22d8f.png)
