### ISSUE TITLE
Update solution description

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#18]
- [x] change background colour 
- [x] update app screenshot
- [x] update description
- [x] update colour to match with theme

![image](https://user-images.githubusercontent.com/30463117/159829862-e342355d-98f1-4cba-a8cc-58f00063ee90.png)

--

Content:
(1) Optimising Operation
Linkexpres is a logistic management system that will help you to increase efficiency in order processing, transporting orders to customers, and report generation. 

(2) Central System
Execute your logistic process in a multi-branch environment to ensure seamless & efficient goods movement, without disruption.

--

The following are the screenshots you can use:
**Dashboard page:**
![image](https://user-images.githubusercontent.com/30463117/159848483-05394c19-7d35-4060-90f7-7321c6389fc3.png)

**Shipment page:**
![image](https://user-images.githubusercontent.com/30463117/159848502-0bcbe802-a36c-4ad5-a093-f18f42bc6016.png)

**Incoming shipment page:**
![image](https://user-images.githubusercontent.com/30463117/159848522-c49d099c-db47-4655-8a93-c3a04076a397.png)

**Comment by russel0907** [comment]
Update solution description #18
![Screenshot 2022-03-24 at 17-10-19 Linkexpres - Logistics Management System](https://user-images.githubusercontent.com/94702093/159897363-000980e9-9a0a-4e3e-a051-7d2bf0855ab2.png)
