### ISSUE TITLE
Add ZZAS Logistics testimony

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#21]
- [x] remove pricing
- [x] remove client list
- [x] add ZZAS logistics testimony on the removed section

![image](https://user-images.githubusercontent.com/30463117/159858755-ed95bdf6-911b-4312-a689-9ce3591fa385.png)

ZZAS Logistic:
![zzas_logo-removebg-preview](https://user-images.githubusercontent.com/30463117/159858310-1896b134-385c-4133-8107-778a8a1f6c8d.png)

Description:
We have helped to improve the business efficiency of ZZAS Logistics with Linkexpres by providing a logistics management system that enables the company to manage multiple branches on a single platform. Linkexpres also assisted ZZAS Logistics in processing monthly invoice claims with its centralized and configurable reporting system feature.

**Comment by russel0907** [comment]
Add ZZAS Logistics testimony:
![Screenshot (137)](https://user-images.githubusercontent.com/94702093/159960030-430998d7-ecf1-4054-adcf-6401008c9c22.png)
