### ISSUE TITLE
Edit banner 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#22]
- [x] make banner 100% screen 
- [x] edit banner background to make text standout

Reference:
<img width="1680" alt="Screenshot 2022-03-24 at 2 33 41 PM" src="https://user-images.githubusercontent.com/30463117/159868328-c60a025e-b87c-4e44-868f-4c6172c45fd2.png">

**Comment by russel0907** [comment]
Edited banner:
![Screenshot (133)](https://user-images.githubusercontent.com/94702093/159903577-17dcd4f1-b8f9-410f-9d39-48874c718828.png)
