### ISSUE TITLE
Redesign testimony section to block quote 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#26]
![image](https://user-images.githubusercontent.com/30463117/160338521-e3b26bdd-db14-4acc-be5a-6d5cd465131f.png)

You can refer to the following as your guide:
![image](https://user-images.githubusercontent.com/30463117/160339354-8e3ec47d-8878-4235-94ea-ec4d19e9533e.png)
![image](https://user-images.githubusercontent.com/30463117/160339757-91079f28-5374-42e9-9b51-3a6ce74097fa.png)

**Comment by russel0907** [comment]
Redesign testimony section to block quote:
![Screenshot (154)](https://user-images.githubusercontent.com/94702093/160356585-315ccbdf-e025-4c4f-ae50-ad22abc8dca5.png)
