### ISSUE TITLE
Add navigation menu

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#27]
- [x] add navigation menu
- [x] link each section to respective menu

![image](https://user-images.githubusercontent.com/30463117/160340466-3b45aa53-a85d-4825-a005-d01257654f2d.png)

You can refer to www.kertasdms.com menu:
![image](https://user-images.githubusercontent.com/30463117/160340850-3e94b2c4-0fd2-468a-b89f-d6d85e3a9557.png)

**Comment by russel0907** [comment]
Add navigation menu;
![Screenshot (158)](https://user-images.githubusercontent.com/94702093/160526990-202fabdd-d00b-4d8b-870f-c6ba27b3fbd9.png)
