### ISSUE TITLE
Change banner picture to logistic lorry

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#28]
![image](https://user-images.githubusercontent.com/30463117/160341160-855a4892-da4c-4732-a8ec-c0715934c82a.png)

**Comment by russel0907** [comment]
Change banner picture to logistic lorry;
![Screenshot (155)](https://user-images.githubusercontent.com/94702093/160390823-69a5bca1-4711-448a-be9b-a3f7b562f272.png)
