### ISSUE TITLE
Enlarge screenshot photo

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#30]
![image](https://user-images.githubusercontent.com/30463117/160343955-76422567-fa17-49c1-8482-ae35f680b6f3.png)

**Comment by russel0907** [comment]
Enlarge screenshot photo ;
![Screenshot (157)](https://user-images.githubusercontent.com/94702093/160422744-1e4850a0-4619-41c7-ba6f-46b1a1ecc126.png)
