### ISSUE TITLE
Redesign testimony section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#35]
You can follow the following design for inspiration:
![image](https://user-images.githubusercontent.com/30463117/160517431-a14b71e5-3c44-432c-9230-01fe3cc5d4d9.png)

**Comment by russel0907** [comment]
Redesign testimony section:
![Screenshot (160)](https://user-images.githubusercontent.com/94702093/160544795-e776e7ab-9f8a-4506-ae9e-8aefebd0e65c.png)
