### ISSUE TITLE
Fix web responsiveness to various dimensions

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#39]

**Comment by russel0907** [comment]
Fix web responsiveness to various dimensions.

Mobile Friendly:
![Screenshot (173)](https://user-images.githubusercontent.com/94702093/160748624-efbec024-be9e-4d6f-813f-b92304e7d873.png)
![Screenshot (174)](https://user-images.githubusercontent.com/94702093/160748626-69a05248-2dba-4136-ae37-c05799123440.png)
![Screenshot (175)](https://user-images.githubusercontent.com/94702093/160748630-49f84972-aacf-4c99-a311-dd3a5c7ac4e8.png)


Fix contact section:
![Screenshot (177)](https://user-images.githubusercontent.com/94702093/160748662-d8035727-ee1c-48f1-815e-b17ed1876f8d.png)
