### ISSUE TITLE
Fix nav menu on mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#40]
- [ ] fix menu usability
- [ ] fix menu view on mobile dimension

<img width="559" alt="Screenshot 2022-03-29 at 5 04 18 PM" src="https://user-images.githubusercontent.com/30463117/160575865-c83417b8-1b89-4737-9eb9-786082fbaa30.png">

**Comment by russel0907** [comment]
Fix navigation menu;
![Screenshot (180)](https://user-images.githubusercontent.com/94702093/160759063-72ee7cef-ae01-498f-a375-f16bc63bf621.png)
![Screenshot (181)](https://user-images.githubusercontent.com/94702093/160759068-e44b2c84-dbdc-4c1d-aed6-1c6d0fd6e2cc.png)
