### ISSUE TITLE
Link contact submit button to mailto function

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#42]
![image](https://user-images.githubusercontent.com/30463117/160740715-493ab2fc-db21-453a-bba6-a8ff59406765.png)

**Comment by russel0907** [comment]
Link contact submit button to mail to function; 
![Screenshot (196)](https://user-images.githubusercontent.com/94702093/160985149-39f185b1-c04b-443c-8f65-0717f1614cf4.png)
