### ISSUE TITLE
Fix testimonial responsiveness 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#47]
![image](https://user-images.githubusercontent.com/30463117/160983547-12adec19-9a09-401f-8f73-2d7c86065973.png)

**Comment by russel0907** [comment]
Fix testimonial responsiveness;

Default view;
![Screenshot (202)](https://user-images.githubusercontent.com/94702093/161085833-9a4fad3a-3cf2-48fa-b2f6-00f3d743e71e.png)

Medium view;
![Screenshot (207)](https://user-images.githubusercontent.com/94702093/161085968-28ff04ba-19af-471d-b956-10fa366e04c2.png)

Mobile view;
![Screenshot (205)](https://user-images.githubusercontent.com/94702093/161086109-7c010625-71e5-447c-aa49-0cd4dc481f10.png)
