### ISSUE TITLE
Fix contact us responsiveness

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#48]
![image](https://user-images.githubusercontent.com/30463117/160983715-99fc6ca2-e671-453d-ad4b-b24a281ab32c.png)

**Comment by russel0907** [comment]
Fix contact us responsiveness section ;

default:
![Screenshot (197)](https://user-images.githubusercontent.com/94702093/161002336-02b20190-aef2-46eb-9ace-b72c4b198603.png)

max-width: 1024px
![Screenshot (198)](https://user-images.githubusercontent.com/94702093/161002409-1e5d837d-06ab-4697-bee9-bb8df5ea5652.png)

max-width: 768px
![Screenshot (199)](https://user-images.githubusercontent.com/94702093/161002491-579bbb77-773d-485c-ac29-5581b6e3b559.png)

max-width: 576px
![Screenshot (200)](https://user-images.githubusercontent.com/94702093/161002573-b9b22de8-29ae-48be-8a40-6d9fb3d7dc1a.png)

max-width: 375px
![Screenshot (201)](https://user-images.githubusercontent.com/94702093/161002659-6e354017-d7c4-4c60-81e8-a72fb41471ba.png)
