### ISSUE TITLE
Fix product service responsiveness

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#49]
![image](https://user-images.githubusercontent.com/30463117/160984107-ac0d2534-3537-492b-8e07-984dcd57c3cf.png)

**Comment by russel0907** [comment]
Fix product responsiveness;

default;
![Screenshot (208)](https://user-images.githubusercontent.com/94702093/161177967-8b5d655a-62b6-4e4d-859e-d000f2012567.png)

IPAD view;
![Screenshot (209)](https://user-images.githubusercontent.com/94702093/161177993-8db01903-7672-450b-a754-c4bc2a9c01ea.png)

mobile view;
![Screenshot (211)](https://user-images.githubusercontent.com/94702093/161178011-cb93789b-7857-44bd-a76b-86cc8be0208f.png)
