### ISSUE TITLE
Update contact and footer

### ISSUE THREAD

**Issue by paragasu** [phisoft/linkexpres-web#5]
- [x] Update address & contacts
- [x] Update copyright
- [x] Update social media links
- [x] Redesign theme color to match with logo

![image](https://user-images.githubusercontent.com/30463117/159825317-03026323-a506-4d58-978a-38b6c08a8e56.png)

**Comment by russel0907** [comment]
updated contact, social media link, color theme and footer copyright:
![Screenshot (132)](https://user-images.githubusercontent.com/94702093/159843282-374d7a86-8d6c-45bf-b9eb-7e1e9a281d51.png)
