### ISSUE TITLE
Remove #[object Object] from link

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#51]
<img width="1043" alt="Screenshot 2022-03-31 at 2 12 39 PM" src="https://user-images.githubusercontent.com/30463117/160988373-0581c91d-6425-44eb-9b01-317008a642d2.png">

**Comment by russel0907** [comment]
Remove #[object Object] from link;

![Screenshot (212)](https://user-images.githubusercontent.com/94702093/161199523-7e1f77cd-e4aa-4aaa-b92d-1c8f6a6c2a07.png)

![Screenshot (213)](https://user-images.githubusercontent.com/94702093/161199530-8413c5d8-c276-4d49-bb87-2dff964d72dd.png)

![Screenshot (215)](https://user-images.githubusercontent.com/94702093/161199532-42666854-0751-4fb0-a10f-090e1c6eb908.png)

![Screenshot (216)](https://user-images.githubusercontent.com/94702093/161199534-2b8fe87b-733c-4244-be22-4e3c3d81086f.png)

![Screenshot (217)](https://user-images.githubusercontent.com/94702093/161199536-dcdc1f0a-eebd-4ee7-87a6-477a7a7758eb.png)
