### ISSUE TITLE
Use transparent background

### ISSUE THREAD

**Issue by paragasu** [phisoft/linkexpres-web#58]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/27353/161482906-f16a235d-fcf8-4f45-9c5a-f7120139fb1f.png">

**Comment by russel0907** [comment]
Use transparent background;]

![Screen Shot 2022-04-05 at 13 07 19](https://user-images.githubusercontent.com/94702093/161683356-c3e5dc0b-f4dc-424b-908f-1da265140f94.png)
