### ISSUE TITLE
Update web content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#62]
- [x] change font to Poppins: https://fonts.google.com/specimen/Poppins
- [x] update web content 
- [x] update product photos

To update content following the below mockup:
![MacBook Pro 14_ - 1(3)](https://user-images.githubusercontent.com/30463117/161712699-d78e7d26-07c7-4b57-bb2b-7bca1bc09beb.png)

**Comment by russel0907** [comment]
Update web content ; 

![Screenshot 2022-04-06 at 11-21-14 Linkexpres - Logistics Management System](https://user-images.githubusercontent.com/94702093/161889920-2931f9d0-346e-42d1-9b35-8d53edbfdb70.png)
