### ISSUE TITLE
Fix our client padding 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/linkexpres-web#65]
Our clients padding too much space for various dimensions. Do checking and make necessary modifications.

- [x] fix padding on tablet and mobile view
- [x] make logo center on tablet and mobile view

![image](https://user-images.githubusercontent.com/30463117/161902324-a87ed6b9-8694-4a15-8af7-40341e1962d7.png)
![image](https://user-images.githubusercontent.com/30463117/161902458-410ae52c-0a15-4559-8e6d-77a0a84e79de.png)

**Comment by russel0907** [comment]
Fix our client padding;

Tablet view;
![127 0 0 1_5501_linkexpres-web_index html(iPad Air) (1)](https://user-images.githubusercontent.com/94702093/161930615-72b8c24a-c369-4f3f-80ed-a039e965ca1a.png)

Mobile view;
![127 0 0 1_5501_linkexpres-web_index html(iPhone 12 Pro) (1)](https://user-images.githubusercontent.com/94702093/161930636-8d2de987-6e42-4aa6-a984-5f5d18dfecc0.png)
